### ISSUE TITLE
Explain build process

### ISSUE THREAD

**Issue by ghost** [meefik/tzupdater#2]
Could you explain the build process a little more, e.g. if I want to build it completely from source, which steps have to be executed in which order?

Also `build-dex.sh` is referencing $HOME, but shouldn't be that somewhat linked to ANDROID_HOME instead?

**Comment by meefik** [comment]
Added $ANDROID_SDK_ROOT variable in the commit 3da121b  

Instruction ($TZ_UPDATER - home directory of the project):
1. Build ZoneCompactor.dex:
   cd $TZ_UPDATER/contrib/ZoneCompactor
   ANDROID_SDK_ROOT="/path/to/AndroidSdk" ./build-dex.sh
   cp ZoneCompactor.dex $TZ_UPDATER/app/src/main/assets/all/bin/ZoneCompactor.dex
2. Build icupkg binary:
   a. Prepare Debian ARM distribution (you can use QEMU)
   b. Copy build-icupkg.sh to the distribution
   c. Execute script build-icupkg.sh
   d. Copy icu/source/bin/icupkg to $TZ_UPDATER/app/src/main/assets/arm/bin/icupkg
3. Build zic binary:
   a. Prepare Debian ARM distribution (you can use QEMU)
   b. Copy build-zic.sh to the distribution
   c. Execute script build-zic.sh
   d. Copy tzcode/zic to $TZ_UPDATER/app/src/main/assets/arm/bin/zic
