### ISSUE TITLE
[1.0.3-19]Unable to get tzdata

### ISSUE THREAD

**Issue by DragonZX** [meefik/tzupdater#3]
Log included
[tzupdater.log](https://github.com/meefik/tzupdater/files/1503045/tzupdater.log)
Update: looks like a busybox bug, also busybox from the neighbourhood said, that it's updated, but tzupdater is using the old one.

**Comment by meefik** [comment]
Please install BusyBox https://github.com/meefik/busybox

**Comment by jcormier** [comment]
Ran into this on my android 4.2 device.  The wget from my busybox does not support https.  I was able to get things working by using http instead of https in the tzdata-updater.sh script.

**Comment by meefik** [comment]
This BusyBox https://github.com/meefik/busybox use `ssl_helper` for SSL support.
