### ISSUE TITLE
icupkg: .res format version 03.00 not supported

### ISSUE THREAD

**Issue by iegubkin** [meefik/tzupdater#4]
Timezone Updater 1.0.3
Android 8.1.0
Updating ICU data now fails with the following error:
```
+ printf 'Updating icudt58l.dat ... '
Updating icudt58l.dat ... + icupkg -s /data/user/0/ru.meefik.tzupdater/files/tmp -a zoneinfo64.res /system/usr/icu/icudt58l.dat
icupkg: .res format version 03.00 not supported, or bundle malformed
+ '[' 16 -eq 0 ']'
+ printf 'fail\n'
fail
+ return 1
+ restore
```
According to users on the forum http://4pda.ru/forum/index.php?showtopic=692805&st=60 the issue seems to be an out-of-date icupkg package. 
Thanks for your work on this most helpful program!

**Comment by meefik** [comment]
Thanks for the reminder, I'm already preparing an update.
