### ISSUE TITLE
Failure to update icudt58l

### ISSUE THREAD

**Issue by mindbound** [meefik/tzupdater#6]
The update fails with the following error:
> icupkg: not an ICU data file: "/data/user/0/ru.meefik.tzupdater/files/tmp/zoneinfo64.res"

I'm using Blackview BV9500 Pro, Android 8.1.

**Comment by meefik** [comment]
Please try v1.2.0 https://github.com/meefik/tzupdater/releases/tag/1.2.0

**Comment by mindbound** [comment]
That solved it, thank you.
